# Prototype Analysis for JIBE project

This Rmarkdown file provides an example multimodal analysis from origins to destinations to inform modelling in the JIBE project.

It uses r5r, an implementation of Conveyal's R5 routing engine for R.  The R5 software evolved from OpenTripPlanner v1, which was its prototype, and is [recommended](http://docs.opentripplanner.org/en/latest/Version-Comparison/) for use for analytical scenarios such as this one. The r5r library was also recommended as the fastest option in a recent paper, **Higgins, C., Palm, M., DeJohn, A., Xi, L., Vaughan, J., Farber, S., Widener, M., & Miller, E. (2022). Calculating place-based transit accessibility: Methods, tools and algorithmic dependence. Journal of Transport and Land Use, 15(1), 95–116. https://doi.org/10.5198/jtlu.2022.2012**.  The analysis drew upon the r5r [vignette](https://cran.r-project.org/web/packages/r5r/vignettes/intro_to_r5r.html).

# Prerequisites:
The installation of Java 11 is required, along with r5r and other packages used in vignette below if required.

The analysis was run using R 4.0.3, within RStudio 1.4

```
install.packages('r5r')
install.packages('leafgl')
```

# Setup
```
# Increase memory available
options(java.parameters = "-Xmx4G")

#Load libraries
library(r5r)
library(sf)
library(data.table)
library(ggplot2)
library(mapview)
mapviewOptions(platform = 'leafgl')

# Set the path to your project director

data_path <- "C:/Users/carlh/OneDrive - RMIT University/projects/JIBE/multimodal_analysis_example"
list.files(data_path)
```
The project directory should contain:
- an OSM excerpt for the region of interest, (http://download.openstreetmap.fr/extracts/oceania/australia/)
- a GTFS.zip file (https://transitfeeds.com/p/ptv/497/20190920/download), 
- and data containing origin and destination locations in EPSG:4326 CRS


# Analysis
```
points <- fread(file.path(data_path, "workEduTrips_longlat.csv"))

origins <- data.table()
origins[,c('id','lon','lat')] <- points[,c('id','ORIGLONG','ORIGLAT')]

destinations <- data.table()
destinations[,c('id','lon','lat')] <- points[,c('id','DESTLONG','DESTLAT')]

# set up
r5r_core <- setup_r5(data_path = data_path, verbose = FALSE)


# set inputs
modes <- c("BICYCLE","CAR","BUS","RAIL","TRAM","TRANSIT")
departure_datetime <- as.POSIXct("16-10-2019 07:45:00",
                                 format = "%d-%m-%Y %H:%M:%S")

results <- list()

for (mode in modes){
  # calculate a travel time matrix
  results[mode] <- detailed_itineraries(  
                      r5r_core,
                      origins,
                      destinations,
                      mode = mode,
                      mode_egress = "WALK",
                      departure_datetime = departure_datetime,
                      max_walk_dist = Inf,
                      max_bike_dist = Inf,
                      max_trip_duration = 120L,
                      walk_speed = 3.6,
                      bike_speed = 12,
                      max_rides = 1,
                      max_lts = 2,
                      shortest_path = TRUE,
                      n_threads = Inf,
                      verbose = FALSE,
                      progress = TRUE,
                      drop_geometry = TRUE
                    )
  fwrite(results[mode], data_path + "/results_"+mode+".csv")
}
```
